-- !Ups

CREATE TABLE `USER` (
    `USER_ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `USERNAME` VARCHAR(255) UNIQUE NOT NULL,
    `PASSWORD` VARCHAR(255)
);

INSERT INTO `USER` (
    `USERNAME`
) VALUES (
    'admin'
);

-- !Downs

DROP TABLE `USER`;